common:
  seed: 12345
  batch_size: 4
  learning_rate: 5e-5
  num_train_epochs: 5
  dataset_path: /opt/ml/final-project-level3-nlp-10/ml/data/project_dataset
wandb:
  project_name: Final_FiD_trial
  entity_name: boost2end
dpr:
  emb_save_path: /opt/ml/final-project-level3-nlp-10/ml/data/dense_embeddings/project/
  #emb_save_path: /opt/ml/final-project-level3-nlp-10/ml/data/mrc_dense_embeddings/train
  encoder_tokenizer: klue/bert-base
  do_eval: True
  eval:
    p_encoder_path: model/saved_models/klue_bert-base/p_encoder
    q_encoder_path: model/saved_models/klue_bert-base/q_encoder
  train:
    test_sample: -1
    neg_num: 7

fid:
  encoder_tokenizer: klue/bert-base
  p_encoder_path: model/saved_models/klue_bert-base/p_encoder
  q_encoder_path: model/saved_models/klue_bert-base/q_encoder
  reader_model: alaggung/bart-r3f
  topk: 5